import themes from "daisyui/src/theming/themes";

const config = {
  appName: "Minimal Market",
  appDescription:
    "The personalized daily text service delivering all the information you need to start the day",
  domainName: "goodmornin.app",
  mailgun: {
    subdomain: "mg",
    fromNoReply: `GoodMornin <noreply@mg.goodmornin.app>`,
    fromAdmin: `Matt at GoodMornin <matt@mg.goodmornin.app>`,
    supportEmail: "matt@mg.goodmornin.app",
    forwardRepliesTo: "matthewtiti@gmail.com",
  },
  colors: {
    theme: "dark",
    main: themes["light"]["primary"],
    toast: "#eab308",
  },
  auth: {
    loginUrl: "/api/auth/signin",
    callbackUrl: "/custom",
  },
  googleAnalyticsId: "",
  screenTimeProjects: [
    {
      id: 1,
      name: "RescueTime",
      tagline: "Understand your habits",
      picture: "/rescuetime_logo.jpeg",
      description: "Tracks app and website usage to reduce screen time.",
      types: ["Mobile", "Web"],
      siteUrl: "https://www.rescuetime.com",
    },
    {
      id: 2,
      name: "Freedom",
      tagline: "Block distractions",
      picture: "/freedom_app_logo.webp",
      description: "Blocks distracting websites and apps across devices.",
      types: ["Mobile", "Web", "Extension"],
      siteUrl: "https://freedom.to",
    },
    {
      id: 4,
      name: "Forest",
      tagline: "Stay focused, grow trees",
      picture: "/forest_logo.png",
      description: "Stay focused by growing a tree when you avoid your phone.",
      types: ["Mobile"],
      siteUrl: "https://www.forestapp.cc",
    },
    {
      id: 5,
      name: "Stay Focused",
      tagline: "App blocker",
      picture: "/stay_focused_logo.png",
      description: "Block apps that waste your time.",
      types: ["Mobile"],
      siteUrl: "https://play.google.com/store/apps/details?id=com.stayfocused",
    },
    {
      id: 7,
      name: "Flipd",
      tagline: "Where the productivity community meets",
      picture: "/flipd_logo.png",
      description:
        "Track your productivity, boost your motivation, and connect with a community of high-achievers like you.",
      types: ["Mobile"],
      siteUrl: "https://www.flipdapp.co",
    },
  ],
  productivityProjects: [
    {
      id: 1,
      name: "Todoist",
      tagline: "Organize your tasks",
      picture: "/todoist_logo.png",
      description: "A task management tool for personal and team productivity.",
      types: ["Mobile"],
      siteUrl: "https://todoist.com",
    },
    {
      id: 2,
      name: "Notion",
      tagline: "Organize your life",
      picture: "/notion_logo.webp",
      description: "A flexible workspace for notes and projects.",
      types: ["Web"],
      siteUrl: "https://notion.so",
    },
    {
      id: 3,
      name: "Trello",
      tagline: "Visual project management",
      picture: "/trello_logo.png",
      description: "Kanban-style boards for managing projects.",
      types: ["Web"],
      siteUrl: "https://trello.com",
    },
    {
      id: 4,
      name: "Be Focused",
      tagline: "Pomodoro timer",
      picture: "/befocused_logo.webp",
      description: "Focus using Pomodoro technique.",
      types: ["Mobile"],
      siteUrl: "https://xwavesoft.com/be-focused-for-ios.html",
    },
    {
      id: 6,
      name: "Habitica",
      tagline: "Gamify your tasks",
      picture: "/habitica-logo.png",
      description:
        "Turn your to-dos into an engaging game that keeps you motivated.",
      types: ["Web"],
      siteUrl: "https://habitica.com",
    },
  ],
  replacementProjects: [
    {
      id: 0,
      name: "GoodMornin",
      tagline: "End the scolling, start your day",
      picture: "/gm-icon.png",
      description:
        "Get a daily text with the top stories and ideas to start your day.",
      types: ["Web"],
      siteUrl: "https://goodmornin.app",
    },
    {
      id: 1,
      name: "Pocket",
      tagline: "Save content for later",
      picture: "/pocket-logo.webp",
      description: "Save articles and videos to view distraction-free later.",
      types: ["Mobile"],
      siteUrl: "https://getpocket.com",
    },
    {
      id: 3,
      name: "Cold Turkey",
      tagline: "Block distractions",
      picture: "/cold_logo.png",
      description: "Aggressive blocker for time-sucking apps and sites.",
      types: ["Desktop"],
      siteUrl: "https://getcoldturkey.com",
    },
    {
      id: 4,
      name: "LeechBlock",
      tagline: "Limit distracting sites",
      picture: "/leech_logo.jpg",
      description: "Blocks distracting websites for set periods.",
      types: ["Extension"],
      siteUrl:
        "https://chromewebstore.google.com/detail/leechblock-ng/blaaajhemilngeeffpbfkdjjoefldkok?hl=en",
    },
    {
      id: 5,
      name: "BlockSite",
      tagline: "Block distracting websites",
      picture: "/block_logo.jpeg",
      description: "Prevent access to time-wasting sites and apps.",
      types: ["Extension"],
      siteUrl: "https://blocksite.co",
    },
    {
      id: 6,
      name: "InboxWhenReady",
      tagline: "Control your email",
      picture: "/inbox_logo.png",
      description: "Hides your inbox on Gmail until you’re ready to check it.",
      types: ["Extension"],
      siteUrl: "https://inboxwhenready.org",
    },
    {
      id: 8,
      name: "Streaks",
      tagline: "Build healthy habits",
      picture: "/streaks_logo.jpg",
      description:
        "Helps users build good habits with daily reminders and progress tracking.",
      types: ["Mobile"],
      siteUrl: "https://streaksapp.com",
    },
  ],
};

export default config;
